/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_epicgames_unreal_AudioVolumeReceiver
#define _Included_com_epicgames_unreal_AudioVolumeReceiver

#ifdef __cplusplus
extern "C" {
#endif

	JNIEXPORT void JNICALL
		Java_com_epicgames_unreal_AudioVolumeReceiver_volumeChanged(JNIEnv* jni, jclass clazz, jint volume);

	JNIEXPORT void JNICALL
		Java_com_epicgames_unreal_AudioVolumeReceiver_ringerModeChanged(JNIEnv* jni, jclass clazz, jboolean isMuted);
#ifdef __cplusplus
}
#endif
#endif