/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class _Included_com_sony_fantom_plugin_auth_FantomAuthWithGoogleNativeAccess */

#ifndef _Included_com_epicgames_unreal_AudioVolumeReceiver
#define _Included_com_epicgames_unreal_AudioVolumeReceiver

#ifdef __cplusplus
extern "C" {
#endif

	JNIEXPORT void JNICALL
		Java_com_epicgames_unreal_AudioVolumeReceiver_volumeChanged(JNIEnv* jni, jclass clazz, jint volume);

#ifdef __cplusplus
}
#endif
#endif
